#!/bin/sh
#
# print the subject
#

for i in $*
do
	echo "$i"
	openssl x509 -subject -issuer -enddate -noout -in $i | sed -e 's#, \([^ ]\+\) = #/\1=#g' -e 's,^\(subject\|issuer\)=\([^ ]\+\) = ,\1= /\2=,g'
	echo "--------"
done