#!/bin/sh

# source: https://gist.github.com/tst2005/797af97fd263677da9e3eede873887ac

for i in $*
do
	echo "$i"
	openssl x509 -subject -issuer -enddate -noout -in $i \
	| sed -e 's#, \([^ ]\+\) = #/\1=#g' -e 's,^\(subject\|issuer\)=\([^ ]\+\) = ,\1= /\2=,g'
	echo "--------"
done